*{box-sizing:border-box}
:root{--bg:#050505;--card:#111;--text:#fff;--muted:#a5a5a5;--line:rgba(255,255,255,.12);--pink:#ff2d70;--purple:#7c5cff}
html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,Arial,sans-serif}
button,input,textarea{font:inherit}
button{cursor:pointer}
.topbar{position:fixed;top:0;left:0;right:0;height:64px;z-index:20;display:flex;align-items:center;justify-content:space-between;padding:0 max(18px,calc((100vw - 1100px)/2));background:linear-gradient(#050505,rgba(5,5,5,.75),transparent);backdrop-filter:blur(8px)}
.logo{font-size:28px;font-weight:900;letter-spacing:-1px;color:#fff;text-decoration:none}.logo span{color:var(--pink)}
.top-actions{display:flex;gap:9px;align-items:center}.search-btn,.profile-btn{width:39px;height:39px;border:1px solid var(--line);border-radius:50%;background:rgba(20,20,20,.75);color:#fff;font-size:21px}.upload-btn{border:0;border-radius:10px;padding:10px 15px;background:#fff;color:#080808;font-weight:800}.upload-btn:hover{transform:translateY(-1px)}
.search-panel{position:fixed;z-index:19;top:64px;left:50%;transform:translateX(-50%) translateY(-15px);width:min(500px,92%);opacity:0;pointer-events:none;transition:.2s}.search-panel.show{opacity:1;transform:translateX(-50%) translateY(0);pointer-events:auto}.search-panel input{width:100%;height:45px;border:1px solid var(--line);border-radius:12px;background:#151515;color:#fff;padding:0 15px;outline:none;box-shadow:0 15px 35px #000}
main{min-height:100vh}.feed{display:flex;flex-direction:column;align-items:center}
.post{position:relative;width:min(100%,520px);height:calc(100vh - 76px);min-height:600px;margin-top:12px;border-radius:18px;overflow:hidden;background:#151515;scroll-snap-align:start;box-shadow:0 10px 40px rgba(0,0,0,.4)}
.post-media{position:absolute;inset:0;background:#080808;display:flex;align-items:center;justify-content:center}.post-media img,.post-media video{width:100%;height:100%;object-fit:cover}.post-media video{background:#000}
.post-overlay{position:absolute;inset:0;background:linear-gradient(transparent 40%,rgba(0,0,0,.04) 48%,rgba(0,0,0,.9) 100%);pointer-events:none}
.post-info{position:absolute;left:18px;right:82px;bottom:24px;z-index:2}.user{font-weight:900;font-size:15px;margin-bottom:8px}.caption{font-size:14px;line-height:1.5;margin:0 0 9px}.time{font-size:11px;color:#c8c8c8}
.side-actions{position:absolute;right:12px;bottom:25px;z-index:3;display:flex;flex-direction:column;gap:17px;align-items:center}.action{border:0;background:none;color:#fff;display:flex;flex-direction:column;align-items:center;gap:4px;text-shadow:0 2px 5px #000}.action-icon{width:46px;height:46px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.35);font-size:25px}.action span:last-child{font-size:11px;font-weight:700}.love.loved .action-icon{color:var(--pink);animation:pop .25s ease}
@keyframes pop{50%{transform:scale(1.35)}}
.play-overlay{position:absolute;inset:0;display:grid;place-items:center;z-index:1;pointer-events:none}.play-circle{width:68px;height:68px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.4);font-size:27px;opacity:0;transition:.2s}.post.paused .play-circle{opacity:1}
.empty{display:none;text-align:center;padding:150px 20px 120px;color:var(--muted)}.empty.show{display:block}.empty-icon{font-size:55px;color:var(--purple)}.empty h2{color:#fff;margin:10px 0}.empty p{max-width:350px;margin:0 auto 20px}
.bottom-nav{position:fixed;z-index:25;bottom:0;left:50%;transform:translateX(-50%);width:min(520px,100%);height:65px;background:rgba(8,8,8,.88);backdrop-filter:blur(18px);border-top:1px solid var(--line);display:flex;justify-content:space-around;align-items:center}.nav-item{border:0;background:none;color:#888;font-size:20px;display:flex;flex-direction:column;align-items:center;gap:2px}.nav-item span{font-size:9px}.nav-item.active{color:#fff}.nav-item:nth-child(2){font-size:27px;color:#fff}
.modal{position:fixed;z-index:100;inset:0;background:rgba(0,0,0,.75);backdrop-filter:blur(7px);display:none;align-items:center;justify-content:center;padding:18px}.modal.show{display:flex}.modal-box{width:min(500px,100%);max-height:90vh;overflow:auto;background:#151515;border:1px solid var(--line);border-radius:20px;padding:25px;position:relative;box-shadow:0 30px 100px #000}.close{position:absolute;right:13px;top:12px;width:34px;height:34px;border:0;border-radius:50%;background:#252525;color:#fff;font-size:22px}.modal-head{text-align:center;margin-bottom:22px}.modal-icon{font-size:32px;color:var(--pink)}.modal h2{margin:5px 0;font-size:25px}.modal-head p{margin:0;color:var(--muted);font-size:13px}.modal form{display:grid;gap:15px}.modal label{display:grid;gap:7px;font-size:12px;font-weight:700}.modal input,.modal textarea{width:100%;border:1px solid var(--line);background:#0b0b0b;color:#fff;border-radius:10px;padding:12px;outline:none}.modal textarea{min-height:100px;resize:vertical}.modal input:focus,.modal textarea:focus{border-color:var(--purple)}.primary{border:0;background:linear-gradient(135deg,var(--purple),#9c63ff);color:#fff;border-radius:10px;padding:13px;font-weight:800}.file-info{font-size:11px;color:var(--muted);margin-top:-8px}.comment-box{width:min(560px,100%)}#commentList{display:grid;gap:9px;max-height:430px;overflow:auto;margin:15px 0}.comment{padding:11px 12px;border-radius:11px;background:#202020}.comment b{font-size:12px}.comment p{margin:3px 0 0;font-size:13px;color:#ddd}.no-comment{color:var(--muted);font-size:13px;padding:20px 0}.comment-form{display:grid!important;grid-template-columns:100px 1fr auto;gap:7px!important}.comment-form input{min-width:0}
.toast{position:fixed;z-index:150;bottom:82px;left:50%;transform:translate(-50%,20px);background:#fff;color:#000;padding:11px 17px;border-radius:10px;font-size:12px;font-weight:800;opacity:0;pointer-events:none;transition:.25s}.toast.show{opacity:1;transform:translate(-50%,0)}
@media(min-width:700px){.feed{padding-bottom:75px}.post{scroll-snap-align:center;margin-bottom:20px}.bottom-nav{border:1px solid var(--line);border-bottom:0;border-radius:18px 18px 0 0}}
@media(max-width:600px){.topbar{height:58px}.topbar .upload-btn{padding:9px 11px;font-size:12px}.logo{font-size:25px}.post{width:100%;height:calc(100vh - 65px);min-height:500px;border-radius:0;margin:0}.post-info{bottom:85px}.side-actions{bottom:90px}.bottom-nav{height:65px}.search-panel{top:57px}.comment-form{grid-template-columns:85px 1fr}.comment-form button{grid-column:1/-1}.comment-form input{width:100%}}
